export type IndexOptionUnderlying = "NIFTY" | "BANKNIFTY";

export const INDEX_OPTION_PROFILE_DEFAULTS: Record<
  IndexOptionUnderlying,
  Record<string, Record<string, unknown>>
> = {
  NIFTY: {
    INDEX_OPTION_MOMENTUM: {
      underlying: "NIFTY",
      interval: "5m",
      emaPeriod: 21,
      useVwap: true,
      breakoutBars: 10,
      strikeOffset: 0,
      stopLossPct: 0.25,
      targetPct: 0.6,
      skipOpenMinutes: 20,
      lastEntryMinutes: 300,
      allowPut: true,
    },
    INDEX_OPTION_FLOW_BREAKOUT: {
      underlying: "NIFTY",
      interval: "5m",
      emaPeriod: 21,
      rsiPeriod: 14,
      breakoutBars: 10,
      strikeOffset: 0,
      volumeMultiple: 1.2,
      sentimentThreshold: 0.2,
      stopLossPct: 0.25,
      targetPct: 0.6,
      skipOpenMinutes: 20,
      lastEntryMinutes: 300,
      allowPut: true,
    },
    INDEX_OPTION_SENTIMENT_FADE: {
      underlying: "NIFTY",
      interval: "5m",
      emaPeriod: 21,
      rsiPeriod: 14,
      oversold: 30,
      overbought: 70,
      swingLookback: 10,
      strikeOffset: 0,
      sentimentThreshold: 0.35,
      stopLossPct: 0.3,
      targetPct: 0.6,
      skipOpenMinutes: 20,
      lastEntryMinutes: 300,
      allowPut: true,
    },
    INDEX_OPTION_PCR_OI: {
      underlying: "NIFTY",
      interval: "5m",
      emaPeriod: 21,
      strikeOffset: 0,
      bullishPcrMin: 1.05,
      bearishPcrMax: 0.75,
      minOiChangePct: 0.05,
      maxChainAgeMinutes: 5,
      stopLossPct: 0.25,
      targetPct: 0.65,
      skipOpenMinutes: 20,
      lastEntryMinutes: 300,
      allowPut: true,
    },
    OPTION_MOMENTUM_SCALPER: {
      underlying: "NIFTY",
      interval: "1m",
      emaFast: 9,
      emaSlow: 20,
      breakoutBars: 5,
      averageVolumePeriod: 20,
      volumeMultiplier: 1.2,
      optionVolumeMultiplier: 1.05,
      minOI: 1000,
      minOIChange: 0,
      minOptionVolume: 100,
      minOptionPriceChangePct: 0.002,
      maxSpreadPercent: 1.5,
      maxChainAgeMinutes: 2,
      maxResistanceOiRatio: 2.5,
      confirmationBars: 0,
      strikeOffset: 0,
      stopLossPct: 0.2,
      targetPct: 0.3,
      skipOpenMinutes: 5,
      lastEntryMinutes: 360,
      allowPut: true,
    },
  },
  BANKNIFTY: {
    INDEX_OPTION_MOMENTUM: {
      underlying: "BANKNIFTY",
      interval: "5m",
      emaPeriod: 13,
      useVwap: true,
      breakoutBars: 8,
      strikeOffset: 0,
      stopLossPct: 0.22,
      targetPct: 0.65,
      skipOpenMinutes: 20,
      lastEntryMinutes: 300,
      allowPut: true,
    },
    INDEX_OPTION_FLOW_BREAKOUT: {
      underlying: "BANKNIFTY",
      interval: "5m",
      emaPeriod: 13,
      rsiPeriod: 14,
      breakoutBars: 8,
      strikeOffset: 0,
      volumeMultiple: 1.35,
      sentimentThreshold: 0.2,
      stopLossPct: 0.22,
      targetPct: 0.65,
      skipOpenMinutes: 20,
      lastEntryMinutes: 300,
      allowPut: true,
    },
    INDEX_OPTION_SENTIMENT_FADE: {
      underlying: "BANKNIFTY",
      interval: "5m",
      emaPeriod: 13,
      rsiPeriod: 14,
      oversold: 30,
      overbought: 70,
      swingLookback: 10,
      strikeOffset: 0,
      sentimentThreshold: 0.35,
      stopLossPct: 0.28,
      targetPct: 0.65,
      skipOpenMinutes: 20,
      lastEntryMinutes: 300,
      allowPut: true,
    },
    INDEX_OPTION_PCR_OI: {
      underlying: "BANKNIFTY",
      interval: "5m",
      emaPeriod: 13,
      strikeOffset: 0,
      bullishPcrMin: 1.05,
      bearishPcrMax: 0.75,
      minOiChangePct: 0.05,
      maxChainAgeMinutes: 5,
      stopLossPct: 0.22,
      targetPct: 0.65,
      skipOpenMinutes: 20,
      lastEntryMinutes: 300,
      allowPut: true,
    },
    OPTION_MOMENTUM_SCALPER: {
      underlying: "BANKNIFTY",
      interval: "1m",
      emaFast: 9,
      emaSlow: 20,
      breakoutBars: 5,
      averageVolumePeriod: 20,
      volumeMultiplier: 1.25,
      optionVolumeMultiplier: 1.05,
      minOI: 1000,
      minOIChange: 0,
      minOptionVolume: 100,
      minOptionPriceChangePct: 0.002,
      maxSpreadPercent: 1.5,
      maxChainAgeMinutes: 2,
      maxResistanceOiRatio: 2.5,
      confirmationBars: 0,
      strikeOffset: 0,
      stopLossPct: 0.2,
      targetPct: 0.3,
      skipOpenMinutes: 5,
      lastEntryMinutes: 360,
      allowPut: true,
    },
  },
};

export function getIndexOptionProfile(
  underlying: IndexOptionUnderlying,
  type: string,
): Record<string, unknown> | null {
  return INDEX_OPTION_PROFILE_DEFAULTS[underlying][type] ?? null;
}

export const INDEX_OPTION_PROFILE_LIST = [
  {
    underlying: "NIFTY" as const,
    type: "INDEX_OPTION_MOMENTUM",
    label: "NIFTY momentum breakout",
  },
  {
    underlying: "NIFTY" as const,
    type: "INDEX_OPTION_FLOW_BREAKOUT",
    label: "NIFTY flow breakout",
  },
  {
    underlying: "NIFTY" as const,
    type: "INDEX_OPTION_SENTIMENT_FADE",
    label: "NIFTY sentiment fade",
  },
  {
    underlying: "NIFTY" as const,
    type: "INDEX_OPTION_PCR_OI",
    label: "NIFTY PCR/OI hybrid",
  },
  {
    underlying: "NIFTY" as const,
    type: "OPTION_MOMENTUM_SCALPER",
    label: "NIFTY option momentum scalper",
  },
  {
    underlying: "BANKNIFTY" as const,
    type: "INDEX_OPTION_MOMENTUM",
    label: "BANKNIFTY momentum breakout",
  },
  {
    underlying: "BANKNIFTY" as const,
    type: "INDEX_OPTION_FLOW_BREAKOUT",
    label: "BANKNIFTY flow breakout",
  },
  {
    underlying: "BANKNIFTY" as const,
    type: "INDEX_OPTION_SENTIMENT_FADE",
    label: "BANKNIFTY sentiment fade",
  },
  {
    underlying: "BANKNIFTY" as const,
    type: "INDEX_OPTION_PCR_OI",
    label: "BANKNIFTY PCR/OI hybrid",
  },
  {
    underlying: "BANKNIFTY" as const,
    type: "OPTION_MOMENTUM_SCALPER",
    label: "BANKNIFTY option momentum scalper",
  },
];
